CREATE TABLE AUDITLOG ( LOGID INTEGER NOT NULL, USERNAME VARCHAR(50), TABLENAME VARCHAR(50) NOT NULL, NEWRECORDID INTEGER, ACTIONDATE TIMESTAMP NOT NULL );
ALTER TABLE AUDITLOG ADD CONSTRAINT PK_AUDITLOG PRIMARY KEY (LOGID);
