CREATE TABLE LOG_FIELDS ( LOG_TABLES_ID INTEGER NOT NULL, FIELD_NAME VARCHAR(67) NOT NULL, OLD_VALUE VARCHAR(255), NEW_VALUE VARCHAR(255) ); 
CREATE INDEX LOG_FIELDS_IDX1 ON LOG_FIELDS (LOG_TABLES_ID); 
