CREATE TABLE LOG_BLOB_FIELDS ( LOG_TABLES_ID INTEGER NOT NULL, FIELD_NAME VARCHAR(67) NOT NULL, OLD_CHAR_VALUE VARCHAR(10000), NEW_CHAR_VALUE VARCHAR(10000), OLD_BLOB_VALUE BLOB SUB_TYPE 0 SEGMENT SIZE 80, NEW_BLOB_VALUE BLOB SUB_TYPE 0 SEGMENT SIZE 80 ); 
CREATE INDEX LOG_BLOB_FIELDS_IDX1 ON LOG_BLOB_FIELDS (LOG_TABLES_ID); 
