CREATE TRIGGER LOG_SS_ACCESSUSER_AI FOR SS_ACCESSUSER 
ACTIVE AFTER INSERT POSITION 32767 
AS
DECLARE VARIABLE TID INTEGER;

BEGIN
  -- Генерация ID для записи в лог
  TID = GEN_ID(LOG_TABLES_GEN, 1);

  -- Основная запись об операции вставки
  INSERT INTO LOG_TABLES (ID, TABLE_NAME, OPERATION, DATE_TIME, USER_NAME)
  VALUES (:TID, 'SS_ACCESSUSER', 'I', 'NOW', USER);

  -- Ключевые поля
  INSERT INTO LOG_KEYS (LOG_TABLES_ID, KEY_FIELD, KEY_VALUE)
  VALUES (:TID, 'ID_ACCESSUSER', NEW.ID_ACCESSUSER);

  INSERT INTO LOG_KEYS (LOG_TABLES_ID, KEY_FIELD, KEY_VALUE)
  VALUES (:TID, 'ID_DB', NEW.ID_DB);

  -- Логирование всех полей (только не-NULL значения)
  IF (NOT (NEW.ID_ACCESSUSER IS NULL)) THEN
    INSERT INTO LOG_FIELDS (LOG_TABLES_ID, FIELD_NAME, OLD_VALUE, NEW_VALUE)
    VALUES (:TID, 'ID_ACCESSUSER', NULL, NEW.ID_ACCESSUSER);

  IF (NOT (NEW.ID_DB IS NULL)) THEN
    INSERT INTO LOG_FIELDS (LOG_TABLES_ID, FIELD_NAME, OLD_VALUE, NEW_VALUE)
    VALUES (:TID, 'ID_DB', NULL, NEW.ID_DB);

  IF (NOT (NEW.ID_PEP IS NULL)) THEN
    INSERT INTO LOG_FIELDS (LOG_TABLES_ID, FIELD_NAME, OLD_VALUE, NEW_VALUE)
    VALUES (:TID, 'ID_PEP', NULL, NEW.ID_PEP);

  IF (NOT (NEW.ID_ACCESSNAME IS NULL)) THEN
    INSERT INTO LOG_FIELDS (LOG_TABLES_ID, FIELD_NAME, OLD_VALUE, NEW_VALUE)
    VALUES (:TID, 'ID_ACCESSNAME', NULL, NEW.ID_ACCESSNAME);

  IF (NOT (NEW.USERNAME IS NULL)) THEN
    INSERT INTO LOG_FIELDS (LOG_TABLES_ID, FIELD_NAME, OLD_VALUE, NEW_VALUE)
    VALUES (:TID, 'USERNAME', NULL, NEW.USERNAME);
END;