CREATE TRIGGER LOG_SS_ACCESSUSER_AU FOR SS_ACCESSUSER 
ACTIVE AFTER UPDATE POSITION 32767 
AS
DECLARE VARIABLE TID INTEGER;

BEGIN
  -- Генерация ID для записи в лог
  TID = GEN_ID(LOG_TABLES_GEN, 1);

  -- Основная запись об операции обновления
  INSERT INTO LOG_TABLES (ID, TABLE_NAME, OPERATION, DATE_TIME, USER_NAME)
  VALUES (:TID, 'SS_ACCESSUSER', 'U', 'NOW', USER);

  -- Ключевые поля (используем OLD значения)
  INSERT INTO LOG_KEYS (LOG_TABLES_ID, KEY_FIELD, KEY_VALUE)
  VALUES (:TID, 'ID_ACCESSUSER', OLD.ID_ACCESSUSER);

  INSERT INTO LOG_KEYS (LOG_TABLES_ID, KEY_FIELD, KEY_VALUE)
  VALUES (:TID, 'ID_DB', OLD.ID_DB);

  -- Логирование изменений ID_ACCESSUSER
  IF ((OLD.ID_ACCESSUSER IS NULL AND NEW.ID_ACCESSUSER IS NOT NULL) OR 
      (NEW.ID_ACCESSUSER IS NULL AND OLD.ID_ACCESSUSER IS NOT NULL) OR 
      (NEW.ID_ACCESSUSER IS NOT NULL AND OLD.ID_ACCESSUSER IS NOT NULL AND NEW.ID_ACCESSUSER <> OLD.ID_ACCESSUSER)) THEN
    INSERT INTO LOG_FIELDS (LOG_TABLES_ID, FIELD_NAME, OLD_VALUE, NEW_VALUE)
    VALUES (:TID, 'ID_ACCESSUSER', OLD.ID_ACCESSUSER, NEW.ID_ACCESSUSER);

  -- Логирование изменений ID_DB
  IF ((OLD.ID_DB IS NULL AND NEW.ID_DB IS NOT NULL) OR 
      (NEW.ID_DB IS NULL AND OLD.ID_DB IS NOT NULL) OR 
      (NEW.ID_DB IS NOT NULL AND OLD.ID_DB IS NOT NULL AND NEW.ID_DB <> OLD.ID_DB)) THEN
    INSERT INTO LOG_FIELDS (LOG_TABLES_ID, FIELD_NAME, OLD_VALUE, NEW_VALUE)
    VALUES (:TID, 'ID_DB', OLD.ID_DB, NEW.ID_DB);
END;