CREATE TRIGGER LOG_SS_ACCESSUSER_AD FOR SS_ACCESSUSER 
ACTIVE AFTER DELETE POSITION 32767 
AS
DECLARE VARIABLE TID INTEGER;

BEGIN
  -- Генерация ID для записи в лог
  TID = GEN_ID(LOG_TABLES_GEN, 1);

  -- Основная запись об операции удаления
  INSERT INTO LOG_TABLES (ID, TABLE_NAME, OPERATION, DATE_TIME, USER_NAME)
  VALUES (:TID, 'SS_ACCESSUSER', 'D', 'NOW', USER);

  -- Ключевые поля (используем OLD значения)
  INSERT INTO LOG_KEYS (LOG_TABLES_ID, KEY_FIELD, KEY_VALUE)
  VALUES (:TID, 'ID_ACCESSUSER', OLD.ID_ACCESSUSER);

  INSERT INTO LOG_KEYS (LOG_TABLES_ID, KEY_FIELD, KEY_VALUE)
  VALUES (:TID, 'ID_DB', OLD.ID_DB);
END;