CREATE TRIGGER SS_ACCESSUSER_AUDIT_AD FOR SS_ACCESSUSER ACTIVE AFTER DELETE POSITION 0 AS BEGIN INSERT INTO AUDITLOG (USERNAME, TABLENAME, NEWRECORDID, ACTIONDATE) VALUES (USER, 'SS_ACCESSUSER', NULL, CURRENT_TIMESTAMP); END; >> tmp.sql
COMMIT; >> tmp.sql
