@echo off
chcp 65001 >nul
echo Создание триггера LOG_PEOPLE_AU...
cd /d "%~dp0"

set ISQL="C:\Program Files (x86)\Firebird\Firebird_1_5_6\bin\isql.exe"
set DB="localhost:C:\Program Files (x86)\Cardsoft\DuoSE\Access\ShieldPro_rest.GDB"

echo CONNECT %DB% USER SYSDBA PASSWORD temp;> tmp.sql
echo SET SQL DIALECT 3;>> tmp.sql
echo SET NAMES WIN1251;>> tmp.sql
echo SET TERM ^;>> tmp.sql
echo CREATE TRIGGER LOG_PEOPLE_AU FOR PEOPLE ACTIVE AFTER UPDATE POSITION 32767 AS DECLARE VARIABLE TID INTEGER; BEGIN TID = GEN_ID(LOG_TABLES_GEN,1); INSERT INTO LOG_TABLES (ID, TABLE_NAME, OPERATION, DATE_TIME, USER_NAME) VALUES (:TID, 'PEOPLE', 'U', 'NOW', USER); INSERT INTO LOG_KEYS (LOG_TABLES_ID, KEY_FIELD, KEY_VALUE) VALUES (:TID, 'ID_PEP', OLD.ID_PEP); INSERT INTO LOG_KEYS (LOG_TABLES_ID, KEY_FIELD, KEY_VALUE) VALUES (:TID, 'ID_DB', OLD.ID_DB); IF ((OLD.ID_PEP IS NULL AND NEW.ID_PEP IS NOT NULL) OR (NEW.ID_PEP IS NULL AND OLD.ID_PEP IS NOT NULL) OR (NEW.ID_PEP IS NOT NULL AND OLD.ID_PEP IS NOT NULL AND NEW.ID_PEP ^<^> OLD.ID_PEP)) THEN INSERT INTO LOG_FIELDS (LOG_TABLES_ID, FIELD_NAME, OLD_VALUE, NEW_VALUE) VALUES (:TID,'ID_PEP',OLD.ID_PEP,NEW.ID_PEP); IF ((OLD.ID_DB IS NULL AND NEW.ID_DB IS NOT NULL) OR (NEW.ID_DB IS NULL AND OLD.ID_DB IS NOT NULL) OR (NEW.ID_DB IS NOT NULL AND OLD.ID_DB IS NOT NULL AND NEW.ID_DB ^<^> OLD.ID_DB)) THEN INSERT INTO LOG_FIELDS (LOG_TABLES_ID, FIELD_NAME, OLD_VALUE, NEW_VALUE) VALUES (:TID,'ID_DB',OLD.ID_DB,NEW.ID_DB); END >> tmp.sql
echo ^;>> tmp.sql
echo SET TERM ;>> tmp.sql
echo COMMIT;>> tmp.sql

%ISQL% -input tmp.sql
del tmp.sql
echo Готово.
pause