@echo off
chcp 65001 >nul
echo Создание триггера LOG_SS_ACCESSUSER_AI...
cd /d "%~dp0"

set ISQL="C:\Program Files (x86)\Firebird\Firebird_1_5_6\bin\isql.exe"
set DB="localhost:C:\Program Files (x86)\Cardsoft\DuoSE\Access\ShieldPro_rest.GDB"

echo CONNECT %DB% USER SYSDBA PASSWORD temp;> tmp.sql
echo SET SQL DIALECT 3;>> tmp.sql
echo SET NAMES WIN1251;>> tmp.sql
echo SET TERM ^;>> tmp.sql
echo CREATE TRIGGER LOG_SS_ACCESSUSER_AI FOR SS_ACCESSUSER ACTIVE AFTER INSERT POSITION 32767 AS DECLARE VARIABLE TID INTEGER; BEGIN TID = GEN_ID(LOG_TABLES_GEN,1); INSERT INTO LOG_TABLES (ID, TABLE_NAME, OPERATION, DATE_TIME, USER_NAME) VALUES (:TID, 'SS_ACCESSUSER', 'I', 'NOW', USER); INSERT INTO LOG_KEYS (LOG_TABLES_ID, KEY_FIELD, KEY_VALUE) VALUES (:TID, 'ID_ACCESSUSER', NEW.ID_ACCESSUSER); INSERT INTO LOG_KEYS (LOG_TABLES_ID, KEY_FIELD, KEY_VALUE) VALUES (:TID, 'ID_DB', NEW.ID_DB); IF (NOT (NEW.ID_ACCESSUSER IS NULL)) THEN INSERT INTO LOG_FIELDS (LOG_TABLES_ID, FIELD_NAME, OLD_VALUE, NEW_VALUE) VALUES (:TID, 'ID_ACCESSUSER', NULL, NEW.ID_ACCESSUSER); IF (NOT (NEW.ID_DB IS NULL)) THEN INSERT INTO LOG_FIELDS (LOG_TABLES_ID, FIELD_NAME, OLD_VALUE, NEW_VALUE) VALUES (:TID, 'ID_DB', NULL, NEW.ID_DB); IF (NOT (NEW.ID_PEP IS NULL)) THEN INSERT INTO LOG_FIELDS (LOG_TABLES_ID, FIELD_NAME, OLD_VALUE, NEW_VALUE) VALUES (:TID, 'ID_PEP', NULL, NEW.ID_PEP); IF (NOT (NEW.ID_ACCESSNAME IS NULL)) THEN INSERT INTO LOG_FIELDS (LOG_TABLES_ID, FIELD_NAME, OLD_VALUE, NEW_VALUE) VALUES (:TID, 'ID_ACCESSNAME', NULL, NEW.ID_ACCESSNAME); IF (NOT (NEW.USERNAME IS NULL)) THEN INSERT INTO LOG_FIELDS (LOG_TABLES_ID, FIELD_NAME, OLD_VALUE, NEW_VALUE) VALUES (:TID, 'USERNAME', NULL, NEW.USERNAME); END >> tmp.sql
echo ^;>> tmp.sql
echo SET TERM ;>> tmp.sql
echo COMMIT;>> tmp.sql

%ISQL% -input tmp.sql
del tmp.sql
echo Готово.
pause