CONNECT "localhost:C:\Program Files (x86)\Cardsoft\DuoSE\Access\ShieldPro_rest.GDB" USER SYSDBA PASSWORD temp; 
SET SQL DIALECT 3; 
SET NAMES WIN1251; 
CREATE GENERATOR LOG_TABLES_GEN; 
CREATE GENERATOR GEN_AUDITLOG_ID; 
COMMIT; 
